/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.collectionsai.config;
import cn.zhuatech.collectionsai.model.*; import cn.zhuatech.collectionsai.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.crypto.password.PasswordEncoder; import java.time.LocalDate; import java.util.List;
@Configuration public class DataInitializer {
 @Bean CommandLineRunner seed(OperatingUnitRepository units,WorkRecordRepository tasks,ResourceRegisterRepository resources,ReviewRecordRepository reviews,UserRepository users,PasswordEncoder encoder){return args->{if(units.count()>0)return;
 var u1=units.save(new OperatingUnit("AR-MGMT","应收管理部","集团财务中心",360));var u2=units.save(new OperatingUnit("AR-EAST","华东应收组","华东财务中心",220));var u3=units.save(new OperatingUnit("AR-RISK","信用风险组","风险管理中心",140));
 var t1=tasks.save(new WorkRecord("CL-260817-068","CUST-0186","华东智造争议账款",u2,5,2,2,LocalDate.now(),WorkRecord.Status.RUNNING,"逾期75天+争议"));var t2=tasks.save(new WorkRecord("CL-260817-064","CUST-0264","远景零售付款承诺",u2,4,3,1,LocalDate.now(),WorkRecord.Status.RUNNING,"逾期32天+承诺"));var t3=tasks.save(new WorkRecord("CL-260817-059","CUST-0418","南辰科技到期提醒",u1,3,1,0,LocalDate.now().plusDays(1),WorkRecord.Status.RELEASED,"逾期16天+提醒"));var t4=tasks.save(new WorkRecord("CL-260816-051","CUST-0082","海洲物流大额催收",u3,6,4,2,LocalDate.now(),WorkRecord.Status.RUNNING,"逾期61天+面谈"));
 resources.saveAll(List.of(new ResourceRegister("ERP-AR","ERP 应收子账",u1,ResourceRegister.Status.RUNNING,99),new ResourceRegister("CRM-360","客户关系与联系人",u2,ResourceRegister.Status.RUNNING,97),new ResourceRegister("BANK-01","银企回款流水",u1,ResourceRegister.Status.IDLE,95)));
 reviews.saveAll(List.of(new ReviewRecord("AP-260817-032",t1,"跨部门协同",5,2,ReviewRecord.Result.PENDING,"叶宁"),new ReviewRecord("AP-260817-027",t2,"承诺确认",4,1,ReviewRecord.Result.PASSED,"陈望"),new ReviewRecord("AP-260817-018",t4,"主管审批",6,2,ReviewRecord.Result.FAILED,"叶宁")));
 String demo=encoder.encode("Demo@2026");users.saveAll(List.of(new UserAccount("operator",demo,"陈望",UserAccount.Role.DOMAIN_USER,"AR-EAST"),new UserAccount("planner",demo,"叶宁",UserAccount.Role.DOMAIN_OPERATOR,null),new UserAccount("quality",demo,"顾清",UserAccount.Role.QUALITY,null),new UserAccount("admin",encoder.encode("ZhuaTech@2026"),"系统管理员",UserAccount.Role.ADMIN,null)));};}
}
