/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'COLLECTIONSAI',systemName:'知华应收催收智能体',englishName:'AI COLLECTIONS WORKBENCH',theme:{primary:'#42644f',dark:'#24372d',accent:'#b9823f'},
 workspace:'集团财务中心 / 应收管理部',fieldWorkspace:'华东应收组 / 催收工作台',period:'2026-08-17 · 月中回款周期',liveText:'应收余额于 14:20 更新',fieldContextLabel:'当前组合',fieldContext:'华东区 · 企业客户',fieldUser:'陈望',fieldRole:'催收专员',adminUser:'叶宁',adminRole:'应收平台主管',
 adminTitle:'应收回款运营中心',adminBreadcrumb:'智能财务 / 催收决策',adminSubtitle:'结合账龄、金额、承诺、争议和客户关系生成可解释的优先级与触达建议。',exportAction:'导出回款预测',createAction:'新建催收策略',chartTitle:'滚动回款达成率',chartSubtitle:'实际回款 / 目标回款',chartLabels:['08-01','08-03','08-05','08-07','08-09','08-11','08-13','08-15','08-17'],loadTitle:'逾期余额结构',loadSubtitle:'按账龄区间与风险计算',recordsTitle:'重点催收任务',recordsSubtitle:'按风险评分、金额和承诺失约排序',issueTitle:'需要协同处理',issueSubtitle:'争议账款、大额暴露和承诺失约',
 recordName:'催收任务',itemName:'客户 / 发票',unitName:'客户经理',batchName:'账龄 / 策略',planName:'触达计划',doneName:'已完成',exceptionName:'异常',unitLabel:'次',listBreadcrumb:'催收决策 / 任务队列',listSubtitle:'优先级、推荐动作、客户反馈和人工审批全部进入回款闭环。',listSummary:[['逾期余额','2,860万'],['本周承诺','1,240万'],['高风险','36',true],['已回款','918万']],tabs:['全部','待触达','协商中','争议处理','已回款'],
 fieldBreadcrumb:'催收工作台 / 华东区',fieldTitle:'智能催收工作台',fieldSubtitle:'今日任务 18 个 · 高风险 5 个 · 承诺到期 4 个',fieldSecondary:'查看客户全景',reportAction:'提交沟通结果',fieldNoticeTitle:'ERP 与 CRM 数据已同步',fieldNotice:'应收账户覆盖率 99.1%',steps:['账款识别','风险评分','策略建议','人工沟通','承诺跟进'],documentAction:'查看客户账款',printAction:'导出沟通清单',resourceCardTitle:'应收数据资源',resourceValueLabel:'纳管应收账户',resourceHealthLabel:'数据完整率',quickSubtitle:'催收工作入口',quickActions:[['记录沟通','/shopfloor/report','承诺、争议与下一步'],['客户账款','/shopfloor/material','发票、回款和信用'],['数据状态','/shopfloor/resources','ERP、CRM 与银企直连'],['协同升级','/shopfloor/andon','争议、法务和大额风险']],
 reportDefaults:[1,0],reportTitle:'催收沟通反馈',reportSubtitle:'记录有效联系、付款承诺、争议原因和下次触达。',reportSuccess:'沟通结果已提交',reportPlaceholder:'填写联系人反馈、承诺金额、承诺日期或争议说明',reportFootnote:'争议账款和 20 万元以上动作须人工批准',ruleTitle:'催收决策门禁',ruleSubtitle:'AR-COLLECT · V1.0',rules:[['争议账款','暂停自动触达'],['战略客户','客户经理参与'],['大额暴露','主管审批'],['联系频率','遵守合规限制',true]],fieldTotals:[['18','今日任务'],['5','高风险客户'],['4','承诺今日到期'],['99.1%','账户覆盖率']],
 adminMenus:[['/admin','home','回款运营中心'],['/admin/work-orders','order','催收任务'],['/admin/samples','box','客户账款'],['/admin/schedule','calendar','触达计划'],['/admin/methods','process','策略规则'],['/admin/reviews','quality','审批协同'],['/admin/resources','machine','数据连接'],['/admin/report','chart','回款分析']],fieldMenus:[['/shopfloor','home','催收工作台'],['/shopfloor/report','report','沟通反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','客户账款'],['/shopfloor/resources','machine','数据状态'],['/shopfloor/andon','risk','协同升级',5]],moduleTitles:{tasks:['我的催收任务','查看优先级、金额和下一步'],material:['客户账款全景','统一查看发票、回款与信用记录'],resources:['数据连接中心','查看 ERP、CRM 和银企直连'],andon:['催收协同升级','处理争议、法务和大额风险'],samples:['客户账款','管理应收账户与客户关系'],schedule:['触达计划','安排电话、邮件和客户拜访'],methods:['策略规则','维护风险权重和沟通约束'],reviews:['审批协同','记录主管、业务与法务意见'],report:['回款分析','分析账龄、承诺和回款预测']},
 tagline:'把有限的催收精力，用在最需要的账款上',storyTitle:'识别回款风险，<br/>给出有分寸的下一步',storyText:'AI 提供优先级和理由，催收专员保留客户关系判断，争议与大额动作始终人工审批。',pattern:[1,4,5,8,12,15,17,21,24,28,31,34],loginStats:[['2,860万','逾期余额'],['1,240万','本周承诺'],['36','高风险客户']],loginTitle:'应收回款运营中心',adminDemo:'账龄 / 预测 / 策略',fieldDemo:'任务 / 沟通 / 承诺'}
export const records=[{no:'CL-260817-068',name:'华东智造 / INV-2606128',code:'CUST-0186',unit:'王珂',group:'制造客户',plan:5,done:2,exception:2,due:'今天',batch:'逾期 75 天 / 争议',status:'争议处理',progress:40,priority:'高风险'},{no:'CL-260817-064',name:'远景零售 / INV-2607286',code:'CUST-0264',unit:'陈望',group:'零售客户',plan:4,done:3,exception:1,due:'今天',batch:'逾期 32 天 / 承诺',status:'协商中',progress:75,priority:'关注'},{no:'CL-260817-059',name:'南辰科技 / INV-2608048',code:'CUST-0418',unit:'周妍',group:'科技客户',plan:3,done:1,exception:0,due:'08-18',batch:'逾期 16 天 / 提醒',status:'待触达',progress:33,priority:'正常'},{no:'CL-260816-051',name:'海洲物流 / INV-2606412',code:'CUST-0082',unit:'陈望',group:'物流客户',plan:6,done:4,exception:2,due:'08-17',batch:'逾期 61 天 / 面谈',status:'主管复核',progress:67,priority:'高风险'},{no:'CL-260815-043',name:'博远服务 / INV-2607221',code:'CUST-0356',unit:'王珂',group:'服务客户',plan:4,done:4,exception:0,due:'08-15',batch:'逾期 28 天 / 承诺',status:'已回款',progress:100,priority:'正常'}]
export const resources=[{code:'ERP-AR',name:'ERP 应收子账',unit:'财务系统组',status:'运行中',health:99,value:'1,286',valueUnit:'户',note:'余额更新至 14:20'},{code:'CRM-360',name:'客户关系与联系人',unit:'客户平台组',status:'运行中',health:97,value:'96.8%',valueUnit:'',note:'客户经理映射完整'},{code:'BANK-01',name:'银企回款流水',unit:'资金结算组',status:'复核中',health:95,value:'T+0',valueUnit:'',note:'3 笔回款等待认领'}]
export const reviews=[{no:'AP-260817-032',title:'华东智造争议账款',type:'跨部门协同',detail:'暴露 26 万元 · 叶宁',result:'待确认'},{no:'AP-260817-027',title:'远景零售付款承诺',type:'承诺确认',detail:'08-19 回款 8 万元 · 陈望',result:'通过'},{no:'AP-260817-018',title:'海洲物流大额催收',type:'主管审批',detail:'客户已两次失约',result:'异常'}]
export const adminMetrics=[['逾期余额','2,860 万','较月初下降 6.2%','blue'],['本周已回款','918 万','达成目标 74%','green'],['承诺待兑现','1,240 万','4 笔今日到期','orange'],['高风险暴露','386 万','涉及 36 个客户','red']]
export const fieldMetrics=[['今日任务','18 个','5 个高风险','blue'],['有效联系','12 次','联系成功率 80%','green'],['付款承诺','4 笔','合计 86 万元','orange'],['待协同','3 个','争议或法务事项','slate']]
export const chartActual=[42,48,53,57,61,66,69,72,74],chartTarget=[45,50,55,60,64,68,72,76,80]
export const loads=[['1—30 天',72,'余额 1,080 万'],['31—60 天',58,'余额 760 万'],['61—90 天',41,'余额 620 万'],['90 天以上',26,'余额 400 万']]
export const issues=[['争议','华东智造对交付验收提出异议','已暂停自动触达并转业务确认','待协调'],['承诺','海洲物流第二次未按承诺付款','建议主管参与下一次面谈','待批准'],['认领','3 笔银行回款尚未匹配发票','已通知资金结算组处理','处理中']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
